### ISSUE TITLE
Crash on server start - Caused by: java.lang.IllegalArgumentException: Plugin 'elementaldimensions' attempted to register an alias ('Elemental Dimensions') which contained a space.

### ISSUE THREAD

**Issue by ProsperCraft** [McJty/ElementalDimensions#11] opened 2017-09-05 06:46 UTC
Oddly, no crash report is created, this stacktrace, then exits.

https://gist.github.com/ProsperCraft/1050806942b722f3419e8b711dd90cac

Then this is seen later down the line-

https://gist.github.com/ProsperCraft/900a01dd813183ea4389d93ea9f0a00c

Full Forge server log here - https://gist.github.com/ProsperCraft/634f3c8327593afeda063161afb08c11

**Comment by McJty** [comment] 2017-09-05 07:05
The space in the command alias will be fixed next release but the crash you pasted after that seems to be caused by sponge. Please report to them.

**Closed as completed by McJty** 2017-09-05 07:05 UTC

**Comment by bloodmc** [comment] 2017-09-15 13:46
@McJty The crash is caused by Sponge since command names should never contain spaces. They should also be lowercase. It seems you referenced the wrong var on this line

https://github.com/McJty/ElementalDimensions/blob/master/src/main/java/bitmovers/elementaldimensions/util/command/ElementalDimensionsCommand.java#L33

Once that is corrected, Sponge should no longer crash. I'll push a workaround to just force the command to be lowercase and not contain spaces. This would be better than crashing =)
